name: Lint

on:
  push:
    branches:
      - main
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [main]

jobs:
  dockerfile:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile

  client:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    name: client lint
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
    - run: cd client && npm run ci && npm run check

  server:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    name: client lint
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
    - run: cd server && npm run ci && npm run check
